#!/usr/bin/env bash
# A bash script that displays Best School 10 times.

# Define the words to be printed
word="Best School"

# Printing the words with for loop
for (( i=1; i<=10; i++ )); do
	echo "$word"
done
